version: "3"
services:
  server:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:80"
      - "5173:80"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
      - /var/www/html:/var/www/html
    depends_on:
      - php
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    restart: unless-stopped
    volumes:
      - /var/www/html:/var/www/html:delegated
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - /var/www/html:/var/www/html
  artisan: 
    build:
      context: ./dockerfiles 
      dockerfile: php.dockerfile
    volumes:
      - /var/www/html:/var/www/html
    entrypoint: ["php","/var/www/html/artisan"]
  npm:
    image: node:latest
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - /var/www/html:/var/www/html