name: Build Assets
on: [push, workflow_dispatch]
jobs:
  run-composer:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Git Repository
        uses: actions/checkout@v3
        # with:
        #   repository: ""
      - name: PHP Install
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Run composer
        run: composer install --no-interaction
      - name: Run npm
        run: npm ci
      - name: Run build
        run: npm run build
