name: Build Assets
on: [push, workflow_dispatch]
env:
  IMAGE_TAG: ""
jobs:
  run-composer:
    runs-on: ubuntu-latest
    steps:
      - name: Put current date into a variable
        run: echo "IMAGE_TAG1=$(date +'%d%m%Y-%H%M')" >> $GITHUB_ENV
      - name: CheckOut Git Repository
        uses: actions/checkout@v3
        # with:
        #   repository: ""
      - name: PHP Install
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Run composer
        run: composer install --no-interaction
      - name: COPY env file
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run npm
        run: npm install
      - name: Run build
        run: npm run build
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: dhawlesudhir@gmail.com
          DOCKER_PASSWORD: practice@0106
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build docker image
        run: docker build -t dhawlesudhir/laravel-app:$IMAGE_TAG1 .
      - name: Push to Dockerhub
        run: docker push dhawlesudhir/laravel-app:$IMAGE_TAG1
