name: Build Assets
on:
  workflow_dispatch:
  push:
    branches:
      - production
jobs:
  build-asset:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{steps.set-image-tag.outputs.image-tag}}
    steps:
      - name: Put current date into a variable
        id: set-image-tag
        run: echo "image-tag=$(date +'%d%m%Y-%H%M')" >> $GITHUB_OUTPUT
      - name: CheckOut Git Repository
        uses: actions/checkout@v3
        # with:
        #   repository: ""
      - name: PHP Install
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Run composer
        run: composer install --no-interaction
      - name: COPY env file
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run npm
        run: npm install
      - name: Run build
        run: npm run build
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: dhawlesudhir@gmail.com
          DOCKER_PASSWORD: practice@0106
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build docker image
        run: docker build -t dhawlesudhir/laravel-app:${{steps.set-image-tag.outputs.image-tag}} .
      - name: Push to Dockerhub
        run: docker push dhawlesudhir/laravel-app:${{steps.set-image-tag.outputs.image-tag}}
  # pull-run-image:
  #   needs: build-asset
  #   runs-on: self-hosted
  #   env:
  #     IMAGE_TAG: ${{ needs.build-asset.outputs.image-tag }}
  #   steps:
  #     - name: Display IMAGE_TAG
  #       run: echo $IMAGE_TAG
  #     - name: Pull latest Image
  #       run: docker pull dhawlesudhir/laravel-app:$IMAGE_TAG
  #     - name: Run Container
  #       run: docker run -p 8000:8000 -d --rm dhawlesudhir/laravel-app:$IMAGE_TAG
  deploy:
    needs: build-asset
    runs-on: ubuntu-latest
    steps:
      - name: DG App Platform Deploy
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: octopus-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
          images: '[
            {
              "name": "${{ needs.build-asset.outputs.image-tag }}",
              "image":{
                "registry_type": "DOCKER_HUB",
                "registry": "dhawlesudhir",
                "repository": "laravel-app",
                "tag": "${{ needs.build-asset.outputs.image-tag }}"
              },
          ]'
