name: Build Assets
on: [push, workflow_dispatch]
jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Git Repository
        uses: actions/checkout@v3
        # with:
        #   repository: ""
      - name: Install Dependencied
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run build
        run: npm run build
